#服务消费者的配置文件
server:
  port: 8003
spring:
  application:
    name: client
  thymeleaf:
    cache: false
    prefix: classpath:/static/
    suffix: .html
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
#mybatis
mybatis:
  mapper-locations: classpath:/mapper/*Mapper.xml
  type-aliases-package: com.scl.menu.domain