server:
  port: 8002
spring:
  application:
    name: menu
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      username: root
      password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/dborder?useSSL=false&useUnicode=UTF-8&serverTimezone=UTC&allowPublicKeyRetrieval=true
#mybatis
mybatis:
  mapper-locations: classpath:/mapper/*Mapper.xml
  type-aliases-package: com.scl.menu.domain